name: ci

on:
  push:
#    branches: main

jobs:
#  login:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    needs:
    - login
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
    steps:
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - name: Setup Coursier cache
        uses: coursier/cache-action@v6.3

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          sbt docker:publish
      - name: Cleanup lock files
        shell: bash
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                       -name ".lock"                -delete || true